test

diff --git a/.github/workflows/trivy-docker-img-scan.yml b/.github/workflows/trivy-docker-img-scan.yml
--- a/.github/workflows/trivy-docker-img-scan.yml
+++ b/.github/workflows/trivy-docker-img-scan.yml
@@ -22,6 +22,9 @@ jobs:
       - name: List Files in Docker Directory
         run: ls -R docker/
 
+      - name: Check if OpenMetadata Artifact Exists
+        run: ls -R openmetadata-dist/target/ || echo "❌ Directory not found!"
+
       - name: Prepare for Docker Build
         id: prepare
         uses: ./.github/actions/prepare-for-docker-build
@@ -31,6 +34,10 @@ jobs:
 
       - name: Build Docker Image
         run: |
+          if [ ! -f openmetadata-dist/target/openmetadata-*.tar.gz ]; then
+            echo "❌ ERROR: Required artifact openmetadata-*.tar.gz not found!";
+            exit 1;
+          fi
           docker build -t openmetadata/server:latest -f docker/development/Dockerfile .
 
       - name: Run Trivy Image Scan
