test

diff --git a/.github/workflows/trivy-docker-img-scan.yml b/.github/workflows/trivy-docker-img-scan.yml
--- a/.github/workflows/trivy-docker-img-scan.yml
+++ b/.github/workflows/trivy-docker-img-scan.yml
@@ -28,29 +28,29 @@ jobs:
         id: trivy_scan
         uses: aquasecurity/trivy-action@master
         with:
-              scan-type: "image"
-              image-ref: "openmetadata/server:trivy"
-              ignore-unfixed: true
-              severity: "HIGH,CRITICAL"
-              output: "trivy-results.txt"
-          env:
-              TRIVY_DISABLE_VEX_NOTICE: "true"
+          scan-type: "image"
+          image-ref: "openmetadata/server:trivy"
+          ignore-unfixed: true
+          severity: "HIGH,CRITICAL"
+          output: "trivy-results.txt"
+        env:
+          TRIVY_DISABLE_VEX_NOTICE: "true"
     
       - name: Format Trivy Output
         run: |
+          if grep -q "HIGH: [1-9]" trivy-results.txt || grep -q "CRITICAL: [1-9]" trivy-results.txt; then
             echo "## 🚨 Trivy Security Scan Results 🚨" > trivy-results.md
             echo "" >> trivy-results.md
-            if [[ -s trivy-results.txt ]]; then
-              echo "### 🔴 Found HIGH and CRITICAL vulnerabilities:" >> trivy-results.md
-              echo '```' >> trivy-results.md
-              cat trivy-results.txt >> trivy-results.md
-              echo '```' >> trivy-results.md
-            else
-              echo "✅ No HIGH or CRITICAL vulnerabilities found." >> trivy-results.md
-            fi 
+            echo "### 🔴 Found HIGH and CRITICAL vulnerabilities:" >> trivy-results.md
+            echo '```' >> trivy-results.md
+            cat trivy-results.txt >> trivy-results.md
+            echo '```' >> trivy-results.md
+            exit 1  # Fail the job if vulnerabilities are found
+          else
+            echo "✅ No HIGH or CRITICAL vulnerabilities found." >> trivy-results.md
+          fi
   
       - name: Comment Trivy Scan Results on PR
         uses: marocchino/sticky-pull-request-comment@v2
         with:
-            path: trivy-results.md
-  
+          path: trivy-results.md
